Cleanup
cirKITers/masKIT pull request #3
Opened 2021-03-11 11:40 UTC by eileen-kuehn

This PR does some general preparation and cleanup and includes:

* [ ] extension of .gitignore
* [ ] pep8 checking
* [ ] blackened files
* [ ] coverage setup
* [ ] pre-commit hook configuration
* [ ] travis configuration

2021-03-13 14:56 UTC, maxfischer2781 requested changes
Added some minor suggestions, basically just black for CI and type hint fixes.

2021-03-13 14:56 UTC, maxfischer2781 commented on .travis.yml
> +  - python -m coverage run -m pytest
Check formatting as well. Might want to sync that against the commit hook.
```suggestion
script:
  - python -m flake8
  - python -m black
  - python -m coverage run -m pytest
```

2021-03-13 14:56 UTC, maxfischer2781 commented on maskit/masked_parameters.py
> +        amount: int = None,
This also needs a ``from typing import Optional`` at the top of the file.
```suggestion
        amount: Optional[int] = None,
```

2021-03-13 14:56 UTC, maxfischer2781 commented on maskit/masked_parameters.py
> +        ), "Negative values are not supported, plese use PerturbationMode.REMOVE"
```suggestion
        ), "Negative values are not supported, please use PerturbationMode.REMOVE"
```

2021-03-13 14:56 UTC, maxfischer2781 commented on maskit/masked_parameters.py
> +            raise ValueError(
In case you want to support it at a later time. :)
```suggestion
            raise NotImplementedError(
```

2021-03-13 14:56 UTC, maxfischer2781 commented on maskit/masked_parameters.py
> +        amount: int = None,
```suggestion
        amount: Optional[int] = None,
```

2021-03-13 14:56 UTC, maxfischer2781 commented on maskit/masked_parameters.py
> +        amount: int = None,
```suggestion
        amount: Optional[int] = None,
```

2021-03-13 14:56 UTC, maxfischer2781 commented on maskit/masked_parameters.py
> +        amount: int = None,
```suggestion
        amount: Optional[int] = None,
```

2021-03-13 14:56 UTC, maxfischer2781 commented on maskit/masked_parameters.py
>          else:
If this isn't a catch-all branch, consider to check for an enum value here and have a final ``else: raise ValueError(...)``.

2021-03-13 14:56 UTC, maxfischer2781 commented on pyproject.toml
> +]
Makes ``black`` available for the CI and developers.
```suggestion
test = [
    "pytest >=4.3.0",
    "flake8",
    "flake8-bugbear",
    "black",
]
```

2021-03-13 16:01 UTC, pep8speaks commented
Hello @eileen-kuehn! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`main.py`](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/main.py):

> [Line 16:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/main.py#L16): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 80 characters)
> [Line 130:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/main.py#L130): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 80 characters)
> [Line 154:21](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/main.py#L154): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 166:25](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/main.py#L166): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 206:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/main.py#L206): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 80 characters)
> [Line 233:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/main.py#L233): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 80 characters)
> [Line 307:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/main.py#L307): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 80 characters)
> [Line 338:21](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/main.py#L338): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 350:25](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/main.py#L350): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator



* In the file [`maskit/circuits.py`](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/maskit/circuits.py):

> [Line 30:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/maskit/circuits.py#L30): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 80 characters)





* In the file [`maskit/masked_parameters.py`](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/maskit/masked_parameters.py):

> [Line 78:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/maskit/masked_parameters.py#L78): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 80 characters)
> [Line 104:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/maskit/masked_parameters.py#L104): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 80 characters)
> [Line 135:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/maskit/masked_parameters.py#L135): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 80 characters)
> [Line 148:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/maskit/masked_parameters.py#L148): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 80 characters)
> [Line 159:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/maskit/masked_parameters.py#L159): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 80 characters)
> [Line 175:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/maskit/masked_parameters.py#L175): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 80 characters)







* In the file [`tests/test_masked_parameters.py`](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/tests/test_masked_parameters.py):

> [Line 55:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/tests/test_masked_parameters.py#L55): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 80 characters)
> [Line 77:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/tests/test_masked_parameters.py#L77): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 80 characters)
> [Line 90:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/tests/test_masked_parameters.py#L90): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 80 characters)
> [Line 107:81](https://github.com/cirKITers/masKIT/blob/eec58fa268cef1787e88a441d81de5e8d17a2868/tests/test_masked_parameters.py#L107): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 80 characters)

2021-03-15 06:43 UTC, eileen-kuehn commented
@cDenius, could you also take a look before merging? I changed the whole structure... Thanks :)

2021-03-15 07:21 UTC, maxfischer2781 approved these changes
Thanks for the changes. Looks good to go. 👍

2021-03-15 12:40 UTC, merged