Add mask for entangling gates
cirKITers/masKIT pull request #32
Opened 2021-08-11 12:44 UTC by eileen-kuehn

This PR adds functionality to support removal of entangling gates from a given circuit via `Mask`s. Idea to support this feature is to explicitly support lowering the expressivity of a quantum circuit and therefore maybe raising the trainability.

Closes #31.

2021-08-11 16:34 UTC, eileen-kuehn commented
@maxfischer2781, when reviewing, please have a specific look on how the `entangling_mask` is currently handled. I opted for making it optional what requires to test if it is set in case actions are performed. This will probably fail for the `execute` function if the mask is not properly initialised.
Any ideas on this? Further, I am a bit afraid, that this mask might even have not a so well-defined shape... However, I would like to give it a try already. What do you think?

2021-08-31 16:12 UTC, maxfischer2781 requested changes
I've only sprinkled ``is not None``s on the cases that were relying on implicit falseyness. That's somewhat faster and should be more robust if you ever refactor.

Do you think you can hit the ``continue``s with unittests? I can't really comment on whether they work as expected.

2021-08-31 16:12 UTC, maxfischer2781 commented on maskit/masks.py
> +        if self.entangling_mask:
```suggestion
        if self.entangling_mask is not None:
```

2021-08-31 16:12 UTC, maxfischer2781 commented on maskit/masks.py
> +        if self._entangling_mask:
```suggestion
        if self._entangling_mask is not None:
```

2021-08-31 16:12 UTC, maxfischer2781 commented on maskit/circuits.py
> +                masked_circuit.entangling_mask
```suggestion
                masked_circuit.entangling_mask is not None
```

2021-08-31 16:12 UTC, maxfischer2781 commented on maskit/circuits.py
> +                masked_circuit.entangling_mask
```suggestion
                masked_circuit.entangling_mask is not None
```

2021-09-01 11:10 UTC, maxfischer2781 commented
Sorry, I missed your previous comment. TBH I'm not totally sure how exactly *this* change works, so it's hard for me to say how it might affect other things.

Perhaps we should discuss at a literal drawing board. :P

2021-09-01 14:19 UTC, eileen-kuehn commented
> Do you think you can hit the `continue`s with unittests? I can't really comment on whether they work as expected.

I added another unit test that should exactly test for that :) Now you will have to review again!

2021-09-01 19:15 UTC, maxfischer2781 approved these changes
Pretty sneaky just raising the coverage while I was looking... 😜

2021-09-01 19:22 UTC, merged